name: Release Actions

on:
  push:
    branches: master    

jobs:
  linux-generate-sha-actions:
    name: Generate SHA Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Create archive
        run: tar -czvf folder/ci_integrations_linux.tgz folder/ci_integrations_linux
      
      - name: Generate SHA-256 
        run: shasum folder/ci_integrations_linux.tgz > folder/ci_integrations_linux.tgz.sha256

      - name: Upload SHA-256 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci_integrations_linux.tgz.sha256
          path: folder/ci_integrations_linux.tgz.sha256
          if-no-files-found: error

  release-actions:
    name: Release Actions
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [ linux-generate-sha-actions ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Configure GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}  

      - name: Download SHA-256 Artifact
        uses: actions/download-artifact@v2
        with:
          name: ci_integrations_linux.tgz.sha256
          path: folder/
      
      - name: Delete release
        run: |
          gh release delete test-release -y
          git push --delete origin test-release

      - name: Create release
        run: gh release create test-release folder/ci_integrations_linux folder/ci_integrations_linux.tgz.sha256 --prerelease --title 'Test release'
