name: Release Actions

on:
  push:
    branches: master    

jobs:
  release-actions:
    name: Release Actions
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Configure GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}    

      - name: Create sha-256
        run: sha256sum test.txt > hash.sha256.txt

      - name: Create archive
        run: tar -czvf hash.tar.gz hash.sha256.txt

      - name: Create release
        run: gh release create test-release some-snapshot hash.tar.gz --prerelease --title 'Test release'  