name: Release Actions

on:
  push:
    branches: master    

jobs:
  release-actions:
    name: Release Actions
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Configure GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Delete release
        run: |
          gh release delete test-release -y
          git push --delete origin test-release

      - name: Create release
        run: gh release create test-release test.txt --prerelease --title 'Test release snapshot'  