name: Test Actions

on:
  push:
    branches: master    

jobs:
  linux-generate-sha-actions:
    name: Generate SHA Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
      
      - name: Generate SHA-256 
        run: shasum folder/ci_integrations_linux > folder/ci_integrations_linux.sha256

      - name: Upload SHA-256 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci_integrations_linux.sha256
          path: folder/ci_integrations_linux1.sha256
          if-no-files-found: error
